[Gssoc'21] Added a dropdown menu
kritikaparmar-programmer/HealthCheck pull request #145
Opened 2021-04-01 17:30 UTC by arpit456jain

## Related Issuse

we have to go to home page for going for any check after this we can go to any page .

Closes: #144 
#### Describe the changes you've made

https://user-images.githubusercontent.com/55352601/113331793-fb19eb00-933d-11eb-945c-b0be8016d837.mp4

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

2021-04-01 17:32 UTC, arpit456jain commented
@kritikaparmar-programmer I had added the drop down and some hover effect in both mode (dark+light) for easy access.

2021-04-01 18:07 UTC, kritikaparmar-programmer requested changes
Rest it fine.

2021-04-01 18:07 UTC, kritikaparmar-programmer commented on templates/layout.html
> +          Predictions
Rename Predictions to Diseases.

2021-04-01 18:17 UTC, arpit456jain commented on templates/layout.html
> +          Predictions
ok just 1 min

2021-04-01 18:20 UTC, arpit456jain commented
@kritikaparmar-programmer kindly add labels before merging

2021-04-02 07:55 UTC, kritikaparmar-programmer approved these changes
Great 👍

2021-04-02 07:55 UTC, merged

2021-04-02 08:56 UTC, arpit456jain commented
@kritikaparmar-programmer kindly add labels of GSSoC'21 and level as i didn't get any points

2021-04-02 10:31 UTC, arpit456jain commented
@kritikaparmar-programmer  thanks