Adding flask route for malaria model and required frontend pages for the same
kritikaparmar-programmer/HealthCheck pull request #187
Opened 2021-04-13 08:15 UTC by ayush-raj8

Added required changes in app.py , developed frontend pages. modified index.html to add malaria link, modified requirements.txt to add new libraries

##Adding flask route for malaria model and required frontend pages for the same

Adding flask route for malaria model and required frontend pages for the same

Closes: #177 

#### Describe the changes you've made

Added required changes in app.py , developed frontend pages. modified index.html to add malaria link, modified requirements.txt to add new libraries for image processing
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

https://user-images.githubusercontent.com/52033949/114519670-45646b80-9c5e-11eb-9981-2d8974dbefcc.mp4

2021-04-13 10:03 UTC, shubhigupta991 approved these changes
Looks good to me❤️

2021-04-13 10:20 UTC, ayush-raj8 commented
please add appropriate level to this too.

2021-04-15 03:54 UTC, kritikaparmar-programmer requested changes

2021-04-15 03:54 UTC, kritikaparmar-programmer commented on app.py
> +                model = load_model("Models/malaria-model.h5")
why you have loaded the model two times?

2021-04-18 08:26 UTC, kritikaparmar-programmer commented
Hey, @ayush-raj8 please resolve the conflicts.

2021-04-18 08:33 UTC, ayush-raj8 reviewed
> Hey, @ayush-raj8 please resolve the conflicts.

Conflict has been resolved.  Removed the redundant line , check apps.py
![image](https://user-images.githubusercontent.com/52033949/115139304-cb155c00-a04e-11eb-8c95-8794643cea7b.png)

2021-04-18 09:08 UTC, merged

2021-04-18 14:56 UTC, ayush-raj8 commented
@kritikaparmar-programmer  @utkarsh0702  please assign level and update it.