Ui improved of website
kritikaparmar-programmer/HealthCheck pull request #200
Opened 2021-04-25 15:54 UTC by arpit456jain

## Related Issuse
Ui improved of website

Closes: #91 

#### Describe the changes you've made

https://drive.google.com/file/d/1g5i6xt__uNyma-Hjobs1VmXxNzMybr7i/view?usp=sharing
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots
![screencapture-127-0-0-1-5000-2021-04-25-21_24_41](https://user-images.githubusercontent.com/55352601/116000157-a7cd4c80-a60c-11eb-995a-f2dc457a6311.png)

2021-04-26 11:56 UTC, arpit456jain commented
@kritikaparmar-programmer kindly review my PR

2021-04-29 04:12 UTC, utkarsh0702 approved these changes

2021-04-29 06:22 UTC, kritikaparmar-programmer requested changes
The rest looks good to me.

2021-04-29 06:22 UTC, kritikaparmar-programmer commented on templates/index.html
one closing div tag missing here.

2021-04-29 06:46 UTC, arpit456jain commented on templates/index.html
Ok let me check

2021-04-29 06:46 UTC, arpit456jain commented
![screencapture-127-0-0-1-5000-2021-04-29-12_16_24](https://user-images.githubusercontent.com/55352601/116511889-c2414780-a8e4-11eb-8fb2-25cb49046f3c.png)

@kritikaparmar-programmer

2021-04-30 11:53 UTC, kritikaparmar-programmer approved these changes

2021-04-30 11:53 UTC, merged

2021-04-30 12:05 UTC, arpit456jain commented
@kritikaparmar-programmer kindly add suitable labels to it 😅😅😅😅

2021-04-30 12:38 UTC, arpit456jain commented
thanks