Create CONTRIBUTING.md
kritikaparmar-programmer/HealthCheck pull request #41
Opened 2021-03-10 05:52 UTC by kcoder63

CONTRIBUTING.md for heath check

2021-03-10 11:49 UTC, kritikaparmar-programmer requested changes

2021-03-10 11:49 UTC, kritikaparmar-programmer commented on CONTRIBUTING.md
> +2. Ensure all Python features used in contributions exist and work in Python 3.8.1 and above.
Make this Python 3.7 or greater. We can use Python 3.7 for this project

2021-03-10 11:49 UTC, kritikaparmar-programmer commented on CONTRIBUTING.md
> + - Python `3.8.1` or greater
Here also make it Python 3.7

2021-03-10 11:49 UTC, kritikaparmar-programmer commented on CONTRIBUTING.md
> +    git commit -am "Meaningful commit message"
change it to  -> git commit -m "Meaningful commit message"

2021-03-10 13:11 UTC, kcoder63 commented
changes done

2021-03-10 18:14 UTC, shubhigupta991 reviewed
Add the issue it resolves

2021-03-10 18:25 UTC, kcoder63 commented
I did mention above

2021-03-11 17:22 UTC, shubhigupta991 approved these changes

2021-03-11 17:23 UTC, merged