Fixed: Updated Readme.md Issue #9
kritikaparmar-programmer/HealthCheck pull request #87
Opened 2021-03-14 18:59 UTC by VivanVatsa

## Related Issue

- Revamped readme.md for tech stack issue #9 

Closes: #9 

#### Describe the changes you've made

- changes made in the technology stack on the readme.md

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

![image](https://user-images.githubusercontent.com/56357691/111080049-a1828580-8522-11eb-90ff-62c71a3adad4.png)

2021-03-15 08:26 UTC, kritikaparmar-programmer requested changes

2021-03-15 08:26 UTC, kritikaparmar-programmer commented on README.md
> +- [Python](https://www.w3schools.com/python/python_intro.asp)
Change Python link to - https://www.python.org/

2021-03-15 08:32 UTC, kritikaparmar-programmer commented
Also, you have done changes to the main branch of your local repo

2021-03-15 08:59 UTC, VivanVatsa commented
yes, I have committed to the main brain of my local repo, do i have to commit the changes in this repo itself?

2021-03-15 13:48 UTC, VivanVatsa commented
fixed with requested changes @kritikaparmar-programmer

2021-03-28 09:08 UTC, kritikaparmar-programmer commented
OK @VivanVatsa merging the pr. Keep contributing :)

2021-03-28 09:08 UTC, merged